### ISSUE TITLE
If the dapp sends an offer to the wallet of the user without a "give", and the user agrees to this offer, then the offer will be accepted even if the smart contract minted less tokens then promised in the offer.

### ISSUE THREAD

**Issue by IlyasMercan** [Agoric/dapp-fungible-faucet#54]
I'm unsure if this is truly an issue. On one hand, under offer safety, a user is guaranteed to either get what they stated they wanted, or get a full refund of what they offered. On the other hand, this isn't a classical offer, since there is no "give" part.

**How to reproduce**
Follow the "starting a project" guide (https://docs.agoric.com/guides/getting-started/start-a-project.html). Before running "agoric deploy ./contract/deploy.js", go to "/src/contract.js" and change the line "const amount = AmountMath.make(brand, 1000n);" to "const amount = AmountMath.make(brand, 250n);".

![issue1](https://user-images.githubusercontent.com/32518684/201541566-78496eaf-133b-442c-82dd-76f6f6c309ad.png)

**Comment by turadg** [comment]
Thanks for the report. As you suspected, this is not a bug.

> user is guaranteed to either get what they stated they wanted, or get a full refund of what they offered

Correct. In this case, the offer was _not satisfied_ so you got back what you offered (nothing). There's no constraint on the contract giving you something anyway (the 250 tokens).

The FungibleFaucet contract could be more careful, but it is within spec. (Zoe enforces offer safety so this contract couldn't violate that if it tried.)
